import netCDF4 as nc
import os
import numpy as np
from matplotlib import pyplot as plt

path = os.getcwd() + '/bfm17/BFM_standalone_pelagic-0515.nc'
variables = nc.Dataset(path).variables

o2 = np.asarray(variables['O2o'][:])
po4 = np.asarray(variables['N1p'][:])
no3 = np.asarray(variables['N3n'][:])
nh4 = np.asarray(variables['N4n'][:])

pc = np.asarray(variables['P2c'][:])
pn = np.asarray(variables['P2n'][:])
pp = np.asarray(variables['P2p'][:])
pl = np.asarray(variables['P2l'][:])
exu = np.asarray(variables['exPPYc'][:])
gpp = np.asarray(variables['ruPPYc'][:])
uptn = np.asarray(variables['ruPPYn'][:])
uptp = np.asarray(variables['ruPPYp'][:])

domc = np.asarray(variables['R1c'][:])
domn = np.asarray(variables['R1n'][:])
domp = np.asarray(variables['R1p'][:])

pomc = np.asarray(variables['R6c'][:])
pomn = np.asarray(variables['R6n'][:])
pomp = np.asarray(variables['R6p'][:])

resz = np.asarray(variables['resZOOc'][:])
nspz = np.asarray(variables['ruZOOc'][:])
zc = np.asarray(variables['Z5c'][:])

remzn = np.asarray(variables['remZOOn'][:])
remzp = np.asarray(variables['remZOOp'])

fI = np.asarray(variables['eiPPY_iiP2_'][:])
ETW = np.asarray(variables['ETW'][:])
EIR = np.asarray(variables['EIR'][:])

x = np.linspace(0,729,730)
# x = np.linspace(15,744,730)

# fig, ax = plt.subplots()
# ax.plot(x,ETW[0:730])
# plt.xlim([0,729])
# # ax.plot(x,ETW[15:745])
# # plt.xlim([15,744])
# plt.title("Temperature")
# plt.xlabel("Time [d]")
# plt.savefig("bfm_temp.jpg")

# fig, ax = plt.subplots()
# ax.plot(x,EIR[0:730])
# plt.xlim([0,729])
# # ax.plot(x,EIR[15:745])
# # plt.xlim([15,744])
# plt.title("Irradiance")
# plt.xlabel("Time [d]")
# plt.savefig("bfm_irr.jpg")

# fig, ax = plt.subplots()
# ax.plot(x,fI[0:730])
# plt.xlim([0,729])
# # ax.plot(x,fI[15:745])
# # plt.xlim([15,744])
# plt.title("Light Limitation")
# plt.xlabel("Time [d]")
# plt.savefig("bfm_fI.jpg")

# fig, ax = plt.subplots()
# ax.plot(x,gpp[0:730])
# plt.xlim([0,729])
# # ax.plot(x,gpp[15:745])
# # plt.xlim([15,744])
# plt.title("Phyto GPP")
# plt.xlabel("Time [d]")
# plt.savefig("bfm_gpp.jpg")

# fig, ax = plt.subplots()
# ax.plot(x,exu[0:730])
# plt.xlim([0,729])
# # ax.plot(x,exu[15:745])
# # plt.xlim([15,744])
# plt.title("Phyto Exudation")
# plt.xlabel("Time [d]")
# plt.savefig("bfm_exu.jpg")

# fig, ax = plt.subplots()
# ax.plot(x,o2[0:730])
# plt.xlim([0,729])
# # ax.plot(x,o2[15:745])
# # plt.xlim([15,744])
# plt.title("Oxygen")
# plt.xlabel("Time [d]")
# plt.ylabel("mmol O / m3")
# plt.savefig("bfm_o2.jpg")

# fig, ax = plt.subplots()
# ax.plot(x,nh4[0:730])
# plt.xlim([0,729])
# # ax.plot(x,nh4[15:745])
# # plt.xlim([15,744])
# plt.title("Ammonium")
# plt.xlabel("Time [d]")
# plt.ylabel("mmol N / m3")
# plt.savefig("bfm_nh4.jpg")

# fig, ax = plt.subplots()
# ax.plot(x,no3[0:730])
# plt.xlim([0,729])
# # ax.plot(x,no3[15:745])
# # plt.xlim([15,744])
# plt.title("Nitrate")
# plt.xlabel("Time [d]")
# plt.ylabel("mmol N / m3")
# plt.savefig("bfm_no3.jpg")

# fig, ax = plt.subplots()
# ax.plot(x,po4[0:730])
# plt.xlim([0,729])
# # ax.plot(x,po4[15:745])
# # plt.xlim([15,744])
# plt.title("Phosphate")
# plt.xlabel("Time [d]")
# plt.ylabel("mmol P / m3")
# plt.savefig("bfm_po4.jpg")

# fig, ax = plt.subplots()
# ax.plot(x,pl[0:730])
# plt.xlim([0,729])
# # ax.plot(x,pl[15:745])
# # plt.xlim([15,744])
# plt.title("Phyto Chl")
# plt.xlabel("Time [d]")
# plt.ylabel("mg Chl / m3")
# plt.savefig("bfm_pl.jpg")

# fig, ax = plt.subplots()
# ax.plot(x,pc[0:730])
# plt.xlim([0,729])
# # ax.plot(x,pc[15:745])
# # plt.xlim([15,744])
# plt.title("Phyto Carbon")
# plt.xlabel("Time [d]")
# plt.ylabel("mg C / m3")
# plt.savefig("bfm_pc.jpg")

# fig, ax = plt.subplots()
# ax.plot(x,pn[0:730])
# plt.xlim([0,729])
# # ax.plot(x,pn[15:745])
# # plt.xlim([15,744])
# plt.title("Phyto Nitrate")
# plt.xlabel("Time [d]")
# plt.ylabel("mmol N / m3")
# plt.savefig("bfm_pn.jpg")

# fig, ax = plt.subplots()
# ax.plot(x,pp[0:730])
# plt.xlim([0,729])
# # ax.plot(x,pp[15:745])
# # plt.xlim([15,744])
# plt.title("Phyto Phosphate")
# plt.xlabel("Time [d]")
# plt.ylabel("mmol P / m3")
# plt.savefig("bfm_pp.jpg")

# fig, ax = plt.subplots()
# ax.plot(x,resz[0:730])
# plt.xlim([0,729])
# # ax.plot(x,pp[15:745])
# # plt.xlim([15,744])
# plt.title("Zoo Respiration")
# plt.xlabel("Time [d]")
# plt.ylabel("mg C / m3")
# plt.savefig("bfm_resz.jpg")

# fig, ax = plt.subplots()
# ax.plot(x,zc[0:730])
# plt.xlim([0,729])
# # ax.plot(x,pc[15:745])
# # plt.xlim([15,744])
# plt.title("Zoo Carbon")
# plt.xlabel("Time [d]")
# plt.ylabel("mg C / m3")
# plt.savefig("bfm_zc.jpg")

# fig, ax = plt.subplots()
# ax.plot(x,pomc[0:730])
# plt.xlim([0,729])
# # ax.plot(x,pc[15:745])
# # plt.xlim([15,744])
# plt.title("POM Carbon")
# plt.xlabel("Time [d]")
# plt.ylabel("mg C / m3")
# plt.savefig("bfm_pomc.jpg")

# fig, ax = plt.subplots()
# ax.plot(x,pomn[0:730])
# plt.xlim([0,729])
# # ax.plot(x,pc[15:745])
# # plt.xlim([15,744])
# plt.title("POM Nitrogen")
# plt.xlabel("Time [d]")
# plt.ylabel("mmol N / m3")
# plt.savefig("bfm_pomn.jpg")

# fig, ax = plt.subplots()
# ax.plot(x,pomp[0:730])
# plt.xlim([0,729])
# # ax.plot(x,pc[15:745])
# # plt.xlim([15,744])
# plt.title("POM Phosphorus")
# plt.xlabel("Time [d]")
# plt.ylabel("mmol P / m3")
# plt.savefig("bfm_pomp.jpg")

# fig, ax = plt.subplots()
# ax.plot(x,domc[0:730])
# plt.xlim([0,729])
# # ax.plot(x,pc[15:745])
# # plt.xlim([15,744])
# plt.title("DOM Carbon")
# plt.xlabel("Time [d]")
# plt.ylabel("mg C / m3")
# plt.savefig("bfm_domc.jpg")

# fig, ax = plt.subplots()
# ax.plot(x,domn[0:730])
# plt.xlim([0,729])
# # ax.plot(x,pc[15:745])
# # plt.xlim([15,744])
# plt.title("DOM Nitrogen")
# plt.xlabel("Time [d]")
# plt.ylabel("mmol N / m3")
# plt.savefig("bfm_domn.jpg")

# fig, ax = plt.subplots()
# ax.plot(x,domp[0:730])
# plt.xlim([0,729])
# # ax.plot(x,pc[15:745])
# # plt.xlim([15,744])
# plt.title("DOM Phosphorus")
# plt.xlabel("Time [d]")
# plt.ylabel("mmol P / m3")
# plt.savefig("bfm_domp.jpg")